In [113]:
import pandas as pd
import numpy as np

In [114]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [115]:
df=pd.read_csv('water_potability.csv')

In [116]:
df.isnull().sum()

ph                 491
Hardness             0
Solids               0
Chloramines          0
Sulfate            781
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64

In [117]:
x=df.drop(['Potability'],axis=1)
y=df['Potability']

In [118]:

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [119]:
pl_1=Pipeline([('si1',SimpleImputer(missing_values=np.NaN,strategy='mean')),('ss1',StandardScaler(),),('dtc',DecisionTreeClassifier())])

In [120]:
pl_1.fit(x_train,y_train)

Pipeline(steps=[('si1', SimpleImputer()), ('ss1', StandardScaler()),
                ('dtc', DecisionTreeClassifier())])

In [121]:
pred=pl_1.predict(x_test)

In [122]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [123]:
print(accuracy_score(pred,y_test))

0.5655487804878049


In [124]:
print(confusion_matrix(y_test,pred))

[[248 164]
 [121 123]]


In [125]:
x_train.isnull().sum()

ph                 395
Hardness             0
Solids               0
Chloramines          0
Sulfate            631
Conductivity         0
Organic_carbon       0
Trihalomethanes    127
Turbidity            0
dtype: int64

In [126]:
print(pl_1)

Pipeline(steps=[('si1', SimpleImputer()), ('ss1', StandardScaler()),
                ('dtc', DecisionTreeClassifier())])


In [127]:
y_train.isnull()

233     False
831     False
2658    False
2495    False
2603    False
        ...  
1095    False
1130    False
1294    False
860     False
3174    False
Name: Potability, Length: 2620, dtype: bool

In [128]:
pl_2=Pipeline([('si1',SimpleImputer(missing_values=np.NaN,strategy='mean')),('ss1',StandardScaler(),),('knn',KNeighborsClassifier())])

In [129]:
pl_2.fit(x_train,y_train)

Pipeline(steps=[('si1', SimpleImputer()), ('ss1', StandardScaler()),
                ('knn', KNeighborsClassifier())])

In [130]:
pred2=pl_2.predict(x_test)

In [131]:
print(accuracy_score(pred2,y_test))
print(confusion_matrix(y_test,pred2))
print(classification_report(y_test,pred2,target_names=['0','1']))

0.6280487804878049
[[310 102]
 [142 102]]
              precision    recall  f1-score   support

           0       0.69      0.75      0.72       412
           1       0.50      0.42      0.46       244

    accuracy                           0.63       656
   macro avg       0.59      0.59      0.59       656
weighted avg       0.62      0.63      0.62       656



In [132]:
pl_3=Pipeline([('si1',SimpleImputer(missing_values=np.NaN,strategy='mean')),('ss1',StandardScaler()),('svc',SVC())])

In [133]:
pl_3.fit(x_train,y_train)
pred2=pl_3.predict(x_test)

In [134]:
print(accuracy_score(pred2,y_test))
print(confusion_matrix(y_test,pred2))
print(classification_report(y_test,pred2,target_names=['0','1']))

0.698170731707317
[[379  33]
 [165  79]]
              precision    recall  f1-score   support

           0       0.70      0.92      0.79       412
           1       0.71      0.32      0.44       244

    accuracy                           0.70       656
   macro avg       0.70      0.62      0.62       656
weighted avg       0.70      0.70      0.66       656



In [135]:
pl=Pipeline([('si1',SimpleImputer(missing_values=np.NaN,strategy='mean')),('knn',KNeighborsClassifier())])
pl.fit(x_train,y_train)
pred=pl.predict(x_test)

In [136]:
print(accuracy_score(pred,y_test))
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred,target_names=['0','1']))

0.5411585365853658
[[295 117]
 [184  60]]
              precision    recall  f1-score   support

           0       0.62      0.72      0.66       412
           1       0.34      0.25      0.29       244

    accuracy                           0.54       656
   macro avg       0.48      0.48      0.47       656
weighted avg       0.51      0.54      0.52       656



In [ ]:
pl_1=Pipeline([('si1',SimpleImputer(missing_values=np.NaN,strategy='mean')),('ss1',StandardScaler(),),('dtc',DecisionTreeClassifier())])